models/product.py
from utils.db import db

class Product(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    nombre = db.Column(db.String(45))
    categoria = db.Column(db.String(45))
    precio = db.Column(db.String(45))
    stock = db.Column(db.Integer)

    def __init__(self, nombre, categoria, precio, stock):
        self.nombre = nombre
        self.categoria = categoria
        self.precio = precio
        self.stock = stock

app.py
from flask import Flask
from routes.products import products
from flask_sqlalchemy import SQLAlchemy
from config import DATABASE_CONNECTION_URI

app = Flask(__name__)

app.secret_key = "secret key"

app.config['SQLALCHEMY_DATABASE_URI'] = DATABASE_CONNECTION_URI
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

SQLAlchemy(app)

app.register_blueprint(products)

routes/products.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from models.product import Product
from utils.db import db

products = Blueprint('products', __name__)

@products.route("/")
def index():
    products = Product.query.all()
    return render_template('index.html', products = products)

@products.route("/new", methods=['POST'])
def add_product():
    nombre = request.form['nombre']
    categoria = request.form['categoria']
    precio = request.form['precio']
    stock = request.form['stock']
    new_product = Product(nombre, categoria, precio, stock)
    db.session.add(new_product)
    db.session.commit()
    flash("Producto AGREGADO con exito")
    return redirect(url_for('products.index'))

@products.route('/update/<id>', methods=["POST", "GET"])
def update(id):
    product = Product.query.get(id)
    if request.method == "POST":
        product.nombre = request.form["nombre"]
        product.categoria = request.form["categoria"]
        product.precio = request.form["precio"]
        product.stock = request.form["stock"]
        db.session.commit()
        return redirect(url_for("products.index"))
    flash("Producto ACTUALIZADO con exito")
    return render_template("update.html", product = product)

@products.route('/delete/<id>')
def delete(id):
    product = Product.query.get(id)
    db.session.delete(product)
    db.session.commit()
    flash("Producto DEPURADO con exito")
    return redirect('/')

@products.route("/about")
def about():
    return render_template('about.html')

templates/about.html
{% extends 'layout.html' %}
    {% block body %}

<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum delectus cumque corporis earum laborum. Quo
    doloribus, modi fugiat, quaerat, unde voluptas nam velit quas illo deleniti mollitia dolores. Quia earum, vero
    distinctio cupiditate recusandae quis minus dicta corrupti! Cupiditate pariatur recusandae laborum maxime sapiente
    fuga tempore hic voluptatibus repellendus possimus iure modi adipisci voluptates, assumenda sed rem delectus in
    facilis iste aperiam nihil aliquam. Reprehenderit nisi autem, velit rem nam provident harum animi modi totam ut
    deleniti voluptatem, labore praesentium perferendis! Dolorem repellendus quidem facilis dolor magni id iusto
    voluptatum atque nostrum ut blanditiis deserunt sed veritatis quod nulla beatae modi ipsam, tempore porro ea quos
    nemo. Tempore reiciendis, in soluta velit fugiat autem optio excepturi, necessitatibus et, eveniet dolore? Culpa
    inventore necessitatibus maiores doloribus temporibus nemo, voluptatum praesentium dolorum iure tempora, cumque
    laborum quisquam reiciendis debitis eum alias aliquid voluptates sint officiis earum! Mollitia pariatur numquam
    officia unde provident quidem facere aut sunt? Laboriosam ipsa perspiciatis qui illo velit fuga officia, nam commodi
    nihil quas inventore esse omnis eligendi necessitatibus! Mollitia ratione tempore pariatur enim totam beatae ab
    similique iure in illum assumenda, eligendi consectetur fugiat, nesciunt porro nulla modi esse earum tenetur
    possimus adipisci. Magni hic veniam consequuntur.</p>

{% endblock %}

templates/index.html
{% extends 'layout.html' %}
    {% block body %}

    <div class="row">
        <div class="col-md-4">
            {% include('partials/_message.html') %}
            {% include('partials/_productForm.html') %}
        </div>

        <div class="col-md-7">
            {% for product in products %}
            <div class="card mb-1 text-white bg-dark">
                <div class="card-body">
                    <div class="d-flex justify-content-between">
                        <h5>{{product.nombre}}</h5>    
                        <div>  
                            <a href="{{ url_for('products.update', id=product.id)}}" class="btn bg-black text-white btn-sm rounded-0">Actualizar</a>
                            <a href="{{ url_for('products.delete', id=product.id)}}" class="btn btn-danger btn-sm rounded-0">Borrar</a>
                        </div>
                    </div>
                <p>Categoria: {{product.categoria}}</p>
                <p>Precio: S/ {{product.precio}} </p>
                <p>Stock: {{product.stock}}</p>
                </div>
            </div>
            {% endfor %}
        </div>

    </div>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tabla Productos CRUD</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

    <link rel="stylesheet" href="{{url_for('static', filename='css/main.css')}}">    
</head>
<body>

    {% include('partials/_navbar.html') %}

    <div class="container p-2">
        {% block body %}
        {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
        crossorigin="anonymous"></script>

</body>
</html>

templates/partials/_message.html
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    {{message}}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}

templates/partials/_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/">Tabla Productos CRUD</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link" href="/about">About</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

templates/partials/_productForm.html
<form action="/new" method="POST" class="card bg-dark text-light">
    <div class="card-body p-4">
        <div class="mb-3">
            <label for="nombre">Nombre</label>
            <input
            type="text"
            name="nombre"
            placeholder="Nombre"
            class="form-control rounded-0 bg-dark border-0 text-white" />
        </div>

        <div class="mb-3">
            <label for="categoria">Categoria</label>
            <input
            type="text"
            name="categoria"
            placeholder="Categoria"
            class="form-control rounded-0 bg-dark border-0 text-white" />
        </div>

        <div class="mb-3">
            <label for="precio">Precio</label>
            <input
            type="text"
            name="precio"
            placeholder="Precio"
            class="form-control rounded-0 bg-dark border-0 text-white" />
        </div>

        <div class="mb-3">
            <label for="stock">Stock</label>
            <input
            type="text"
            name="stock"
            placeholder="Stock"
            class="form-control rounded-0 bg-dark border-0 text-white" />
        </div>

        <button class="btn btn-primary">Save</button>
    </div>

</form>

templates/update.html
{% extends 'layout.html' %}
    {% block body %}

<form action="/update/{{product.id}}" method="POST" class="card bg-dark text-light">
    <div class="card-body p-4">
        <div class="mb-3">
            <label for="nombre">Nombre</label>
            <input
            type="text"
            name="nombre"
            placeholder="Nombre"
            value="{{product.nombre}}"
            class="form-control rounded-0 bg-dark border-0 text-white" />
        </div>

        <div class="mb-3">
            <label for="categoria">Categoria</label>
            <input
            type="text"
            name="categoria"
            placeholder="Categoria"
            value="{{product.categoria}}"
            class="form-control rounded-0 bg-dark border-0 text-white" />
        </div>

        <div class="mb-3">
            <label for="precio">Precio</label>
            <input
            type="text"
            name="precio"
            placeholder="Precio"
            value="{{product.precio}}"
            class="form-control rounded-0 bg-dark border-0 text-white" />
        </div>

        <div class="mb-3">
            <label for="stock">Stock</label>
            <input
            type="text"
            name="stock"
            placeholder="Stock"
            value="{{product.stock}}"
            class="form-control rounded-0 bg-dark border-0 text-white" />
        </div>

        <button class="btn btn-primary">Save</button>
    </div>

</form>

{% endblock %}